# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zulbbp5m57yztUh_2hIJeZby-nRx6FGv

Calculadora
"""

def adicionar(x,y): # definindo funções matemáticas
  return x+y

def subtrair(x,y):
  return x-y

def multiplicar(x,y):
  return x*y

def dividir(x,y):
  if y == 0: # caso tente operação com 0
    return "Não é possível dividir por zero"
  return x/y


def calculadora(): # definindo calculadora com as opções
  print("Selecione a operação:")
  print("1.Adição")
  print("2.Subtração")
  print("3.Multiplicação")
  print("4.Divisão")
  print("5.Sair")

while True:
  calculadora()

  escolha = input("Digite sua opção (1/2/3/4):") # Pedindo a escolha do usuário

  if escolha == '5':
    print('saindo...')
    break

  num1 = float(input("Digite o primeiro número:")) # Defindo variaveis e convertendo para float e inserção delas
  num2 = float(input("Digite o segundo número:"))

  if escolha == '1': # Escolha das operações
    print(num1, "+", num2, "=", adicionar(num1,num2))
  elif escolha == '2':
    print(num1, "-", num2, "=", subtrair(num1,num2))
  elif escolha == '3':
    print(num1, "*", num2, "=", multiplicar(num1,num2))
  elif escolha == '4':
    print(num1, "/", num2, "=", dividir(num1,num2))
  else: # Escolha >= 6
    print("opção inválida")

